import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-[80rem] mx-auto">
          <nav className="px-8 py-4 flex gap-4 bg-purple-600 text-white dark:bg-gray-800 mb-4 font-semibold">
            <div className="flex-1">
              <Link href="/">Recipedia</Link>
            </div>

            <Link href="/categories" className="hover:underline">
              Categories
            </Link>
            <Link href="/favorites" className="hover:underline">
              Favorite Meals
            </Link>
          </nav>
          {children}
        </main>
        <footer className="p-4 text-center text-gray-500 mt-20">
          &copy; 2025 Recipedia. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
