import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 flex gap-4 bg-gray-200 dark:bg-gray-800 mb-20">
          <Link href="/" className="flex-1">
            Recipedia
          </Link>
          <Link href="/">Home</Link>
          <Link href="/categories">Categories</Link>
          <Link href="/favorites">Favorite Meals</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
